#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.7an >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.7an=/luci-static/7an
		set luci.main.mediaurlbase=/luci-static/7an
		commit luci
	EOF
fi

exit 0
